-- V1__init.sql
-- Initial schema migration
-- Add your DDL statements here (CREATE TABLE, sequences, indexes, etc.)

CREATE TABLE toyStore_clients (
                                  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name_customer VARCHAR2(20),
                                  points       NUMBER,
                                  last_sale    NUMBER(15,2),
                                  customer_rd  DATE DEFAULT SYSDATE
);