-- ------------------------------------------------------------
-- TABLE: user_type
-- ------------------------------------------------------------
CREATE TABLE user_type (
                           id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_type   VARCHAR2(50)  NOT NULL UNIQUE,
                           description VARCHAR2(500),
                           created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: users
-- ------------------------------------------------------------
CREATE TABLE users (
                       id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_type_id  NUMBER        NOT NULL,
                       name          VARCHAR2(255) NOT NULL,
                       username      VARCHAR2(50)  NOT NULL UNIQUE,
                       password_hash VARCHAR2(255) NOT NULL,
                       email         VARCHAR2(255) NOT NULL UNIQUE,
                       phone         VARCHAR2(20),
                       created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_users_user_type FOREIGN KEY (user_type_id) REFERENCES user_type (id)
);

-- ------------------------------------------------------------
-- TABLE: projects
-- ------------------------------------------------------------
CREATE TABLE projects (
                          id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name        VARCHAR2(255) NOT NULL,
                          description CLOB,
                          status      VARCHAR2(20)  DEFAULT 'active'
                              CHECK (status IN ('active', 'paused', 'completed', 'cancelled')),
                          start_date  TIMESTAMP,
                          end_date    TIMESTAMP,
                          created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: project_members
-- ------------------------------------------------------------
CREATE TABLE project_members (
                                 id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 project_id NUMBER NOT NULL,
                                 user_id    NUMBER NOT NULL,
                                 role       VARCHAR2(20) DEFAULT 'member'
                                     CHECK (role IN ('owner', 'manager', 'member')),
                                 joined_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 CONSTRAINT fk_pm_project      FOREIGN KEY (project_id) REFERENCES projects (id),
                                 CONSTRAINT fk_pm_user         FOREIGN KEY (user_id)    REFERENCES users (id),
                                 CONSTRAINT uq_pm_project_user UNIQUE (project_id, user_id)
);

-- ------------------------------------------------------------
-- TABLE: sprints
-- ------------------------------------------------------------
CREATE TABLE sprints (
                         id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         project_id  NUMBER         NOT NULL,
                         name        VARCHAR2(100)  NOT NULL,
                         goal        VARCHAR2(1000),
                         status      VARCHAR2(20)   DEFAULT 'planned'
                             CHECK (status IN ('planned', 'active', 'completed')),
                         start_date  TIMESTAMP,
                         due_date    TIMESTAMP,
                         actual_end  TIMESTAMP,
                         created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT fk_sprints_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

-- ------------------------------------------------------------
-- TABLE: tasks
-- ------------------------------------------------------------
CREATE TABLE tasks (
                       id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       project_id  NUMBER         NOT NULL,
                       title       VARCHAR2(255)  NOT NULL,
                       description CLOB,
                       priority    VARCHAR2(10)   DEFAULT 'medium'
                           CHECK (priority IN ('low', 'medium', 'high', 'critical')),
                       status      VARCHAR2(20)   DEFAULT 'todo'
                           CHECK (status IN ('todo', 'in_progress', 'review', 'done')),
                       start_date  TIMESTAMP,
                       due_date    TIMESTAMP,
                       actual_end  TIMESTAMP,
                       created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_tasks_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

-- ------------------------------------------------------------
-- TABLE: task_assignments
-- ------------------------------------------------------------
CREATE TABLE task_assignments (
                                  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  task_id     NUMBER NOT NULL,
                                  user_id     NUMBER NOT NULL,
                                  assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT fk_ta_task      FOREIGN KEY (task_id) REFERENCES tasks (id),
                                  CONSTRAINT fk_ta_user      FOREIGN KEY (user_id) REFERENCES users (id),
                                  CONSTRAINT uq_ta_task_user UNIQUE (task_id, user_id)
);

-- ------------------------------------------------------------
-- TABLE: sprint_tasks
-- ------------------------------------------------------------
CREATE TABLE sprint_tasks (
                              id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              sprint_id  NUMBER NOT NULL,
                              task_id    NUMBER NOT NULL,
                              added_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              removed_at TIMESTAMP,
                              moved_to   NUMBER,
                              CONSTRAINT fk_st_sprint FOREIGN KEY (sprint_id) REFERENCES sprints (id),
                              CONSTRAINT fk_st_task   FOREIGN KEY (task_id)   REFERENCES tasks (id),
                              CONSTRAINT fk_st_moved  FOREIGN KEY (moved_to)  REFERENCES sprints (id)
);

-- ------------------------------------------------------------
-- TABLE: logs
-- ------------------------------------------------------------
CREATE TABLE logs (
                      id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id   NUMBER,
                      entity    VARCHAR2(50),
                      entity_id NUMBER,
                      action    VARCHAR2(50),
                      detail    VARCHAR2(1000),
                      log_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_users_user_type    ON users (user_type_id);
CREATE INDEX idx_pm_project_id      ON project_members (project_id);
CREATE INDEX idx_pm_user_id         ON project_members (user_id);
CREATE INDEX idx_sprints_project_id ON sprints (project_id);
CREATE INDEX idx_tasks_project_id   ON tasks (project_id);
CREATE INDEX idx_st_sprint_id       ON sprint_tasks (sprint_id);
CREATE INDEX idx_st_task_id         ON sprint_tasks (task_id);
CREATE INDEX idx_ta_task_id         ON task_assignments (task_id);
CREATE INDEX idx_ta_user_id         ON task_assignments (user_id);
CREATE INDEX idx_logs_entity        ON logs (entity, entity_id);