-- V1__init.sql
-- Initial schema migration
-- Add your DDL statements here (CREATE TABLE, sequences, indexes, etc.)

CREATE TABLE tasks (
                       id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title        VARCHAR2(200) NOT NULL,
                       description  VARCHAR2(1000),
                       status       VARCHAR2(30) DEFAULT 'TODO' NOT NULL,
                       created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_tasks_status ON tasks(status);