-- ============================================================
-- Oracle Autonomous Database Schema
-- Generated from ER Diagram
-- ============================================================

-- ------------------------------------------------------------
-- TABLE: Rol
-- ------------------------------------------------------------
CREATE TABLE Rol (
                     id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     rol         VARCHAR2(255),
                     description VARCHAR2(255),
                     created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: Proyecto
-- ------------------------------------------------------------
CREATE TABLE Proyecto (
                          id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name             VARCHAR2(255),
                          description      VARCHAR2(255),
                          start_date       TIMESTAMP,
                          end_date         TIMESTAMP,
                          max_sprints      NUMBER,
                          current_sprints  NUMBER,
                          created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: Tasks
-- ------------------------------------------------------------
CREATE TABLE Tasks (
                       id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       task        VARCHAR2(255),
                       description VARCHAR2(255),
                       priority    NUMBER,
                       start_task  TIMESTAMP,
                       end_task    TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: Usuarios
-- ------------------------------------------------------------
CREATE TABLE Usuarios (

                          id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          rol_id        NUMBER,
                          name          VARCHAR2(255),
                          username      VARCHAR2(20)  NOT NULL,
                          password_hash VARCHAR2(20),
                          CONSTRAINT uq_usuarios_username UNIQUE (username),
                          CONSTRAINT fk_usuarios_rol
                              FOREIGN KEY (rol_id) REFERENCES Rol (id)
);

-- ------------------------------------------------------------
-- TABLE: Project_users
-- ------------------------------------------------------------
CREATE TABLE Project_users (
                               id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               project_id  NUMBER         NOT NULL,
                               user_id     NUMBER         NOT NULL,
                               task_id     NUMBER         NOT NULL,
                               sprint      NUMBER,
                               created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT fk_pu_project
                                   FOREIGN KEY (project_id) REFERENCES Proyecto (id),
                               CONSTRAINT fk_pu_user
                                   FOREIGN KEY (user_id)    REFERENCES Usuarios (id),
                               CONSTRAINT fk_pu_task
                                   FOREIGN KEY (task_id)    REFERENCES Tasks (id)
);

-- ------------------------------------------------------------
-- TABLE: Logs
-- ------------------------------------------------------------
CREATE TABLE Logs (
                      id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      log_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- INDEXES (recommended for FK columns on Oracle)
-- ============================================================
CREATE INDEX idx_pu_project_id ON Project_users (project_id);
CREATE INDEX idx_pu_user_id    ON Project_users (user_id);
CREATE INDEX idx_pu_task_id    ON Project_users (task_id);
CREATE INDEX idx_usuarios_rol  ON Usuarios (rol_id);
