-- ============================================================
-- TABLE: TASKS
-- ============================================================
ALTER TABLE tasks DROP COLUMN story_points;
ALTER TABLE tasks DROP COLUMN acceptance_criteria;

ALTER TABLE tasks
    ADD (
        created_by  NUMBER,
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_by  NUMBER,
        updated_at  TIMESTAMP,
        CONSTRAINT fk_tasks_created_by FOREIGN KEY (created_by) REFERENCES users (id),
        CONSTRAINT fk_tasks_updated_by FOREIGN KEY (updated_by) REFERENCES users (id),
        CONSTRAINT chk_tasks_dates     CHECK (updated_at IS NULL OR updated_at >= created_at)
        );

-- ============================================================
-- TABLE: PROJECTS
-- ============================================================
ALTER TABLE projects
    ADD (
        created_by  NUMBER,
        updated_by  NUMBER,
        updated_at  TIMESTAMP,
        CONSTRAINT fk_projects_created_by FOREIGN KEY (created_by) REFERENCES users (id),
        CONSTRAINT fk_projects_updated_by FOREIGN KEY (updated_by) REFERENCES users (id),
        CONSTRAINT chk_projects_dates     CHECK (updated_at IS NULL OR updated_at >= created_at)
        );

-- ============================================================
-- TABLE: SPRINTS
-- ============================================================
ALTER TABLE sprints
    ADD (
        created_by  NUMBER,
        updated_by  NUMBER,
        updated_at  TIMESTAMP,
        CONSTRAINT fk_sprints_created_by FOREIGN KEY (created_by) REFERENCES users (id),
        CONSTRAINT fk_sprints_updated_by FOREIGN KEY (updated_by) REFERENCES users (id),
        CONSTRAINT chk_sprints_dates     CHECK (updated_at IS NULL OR updated_at >= created_at)
        );

-- ============================================================
-- TABLE: CAPABILITIES
-- ============================================================
CREATE TABLE capabilities (
                              id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              project_id  NUMBER        NOT NULL,
                              name        VARCHAR2(255) NOT NULL,
                              description CLOB,
                              status      VARCHAR2(20)  DEFAULT 'active'
                                  CHECK (status IN ('active', 'completed', 'cancelled')),
                              created_by  NUMBER,
                              created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              updated_by  NUMBER,
                              updated_at  TIMESTAMP,
                              CONSTRAINT fk_capabilities_project    FOREIGN KEY (project_id) REFERENCES projects (id),
                              CONSTRAINT fk_capabilities_created_by FOREIGN KEY (created_by) REFERENCES users (id),
                              CONSTRAINT fk_capabilities_updated_by FOREIGN KEY (updated_by) REFERENCES users (id),
                              CONSTRAINT chk_cap_dates              CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE INDEX idx_capabilities_project_id ON capabilities (project_id);

-- ============================================================
-- TABLE: FEATURES
-- ============================================================
CREATE TABLE features (
                          id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          capability_id NUMBER        NOT NULL,
                          name          VARCHAR2(255) NOT NULL,
                          description   CLOB,
                          status        VARCHAR2(20)  DEFAULT 'active'
                              CHECK (status IN ('active', 'completed', 'cancelled')),
                          created_by    NUMBER,
                          created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          updated_by    NUMBER,
                          updated_at    TIMESTAMP,
                          CONSTRAINT fk_features_capability FOREIGN KEY (capability_id) REFERENCES capabilities (id),
                          CONSTRAINT fk_features_created_by FOREIGN KEY (created_by)    REFERENCES users (id),
                          CONSTRAINT fk_features_updated_by FOREIGN KEY (updated_by)    REFERENCES users (id),
                          CONSTRAINT chk_feat_dates         CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE INDEX idx_features_capability_id ON features (capability_id);

-- ============================================================
-- TABLE: USER STORIES
-- ============================================================
CREATE TABLE user_stories (
                              id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              feature_id          NUMBER        NOT NULL,
                              title               VARCHAR2(255) NOT NULL,
                              description         CLOB,
                              acceptance_criteria CLOB,
                              priority            VARCHAR2(10)  DEFAULT 'medium'
                                  CHECK (priority IN ('low', 'medium', 'high', 'critical')),
                              status              VARCHAR2(20)  DEFAULT 'todo'
                                  CHECK (status IN ('todo', 'in_progress', 'review', 'done')),
                              story_points        NUMBER(3),
                              owner_id            NUMBER,
                              created_by          NUMBER        NOT NULL,
                              created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              updated_by          NUMBER,
                              updated_at          TIMESTAMP,
                              CONSTRAINT fk_us_feature    FOREIGN KEY (feature_id) REFERENCES features (id),
                              CONSTRAINT fk_us_owner      FOREIGN KEY (owner_id)   REFERENCES users (id),
                              CONSTRAINT fk_us_created_by FOREIGN KEY (created_by) REFERENCES users (id),
                              CONSTRAINT fk_us_updated_by FOREIGN KEY (updated_by) REFERENCES users (id),
                              CONSTRAINT chk_us_dates     CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE INDEX idx_us_feature_id ON user_stories (feature_id);

-- ============================================================
-- TABLE: USER STORY DEPENDENCIES
-- ============================================================
CREATE TABLE user_story_dependencies (
                                         id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         story_id        NUMBER       NOT NULL,
                                         blocked_by_id   NUMBER       NOT NULL,
                                         dependency_type VARCHAR2(20) DEFAULT 'blocks' NOT NULL
                                             CHECK (dependency_type IN (
                                                                        'blocks',
                                                                        'related',
                                                                        'duplicates',
                                                                        'split_from',
                                                                        'parent_child'
                                                 )),
                                         created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                         CONSTRAINT fk_usd_story      FOREIGN KEY (story_id)      REFERENCES user_stories (id),
                                         CONSTRAINT fk_usd_blocked_by FOREIGN KEY (blocked_by_id) REFERENCES user_stories (id),
                                         CONSTRAINT uq_usd_pair       UNIQUE (story_id, blocked_by_id),
                                         CONSTRAINT chk_usd_no_self   CHECK  (story_id != blocked_by_id)
);

CREATE INDEX idx_usd_story_id      ON user_story_dependencies (story_id);
CREATE INDEX idx_usd_blocked_by_id ON user_story_dependencies (blocked_by_id);

-- ============================================================
-- TABLE: SPRINT STORIES
-- ============================================================
CREATE TABLE sprint_stories_assignments (
                                            id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            sprint_id     NUMBER    NOT NULL,
                                            user_story_id NUMBER    NOT NULL,
                                            added_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                            removed_at    TIMESTAMP,
                                            moved_to      NUMBER,
                                            is_active     NUMBER(1) DEFAULT 1 NOT NULL
                                                CHECK (is_active IN (0, 1)),
                                            CONSTRAINT fk_ss_sprint FOREIGN KEY (sprint_id)     REFERENCES sprints (id),
                                            CONSTRAINT fk_ss_story  FOREIGN KEY (user_story_id) REFERENCES user_stories (id),
                                            CONSTRAINT fk_ss_moved  FOREIGN KEY (moved_to)      REFERENCES sprints (id)
);

CREATE UNIQUE INDEX uq_ss_one_active
    ON sprint_stories_assignments (
                                   CASE WHEN is_active = 1 THEN sprint_id     ELSE NULL END,
                                   CASE WHEN is_active = 1 THEN user_story_id ELSE NULL END
        );

CREATE INDEX idx_ss_sprint_id ON sprint_stories_assignments (sprint_id);
CREATE INDEX idx_ss_story_id  ON sprint_stories_assignments (user_story_id);

-- ============================================================
-- LINK TASKS WITH USER STORIES
-- ============================================================
ALTER TABLE tasks
    ADD user_story_id NUMBER;

ALTER TABLE tasks
    ADD CONSTRAINT fk_tasks_user_story
        FOREIGN KEY (user_story_id) REFERENCES user_stories (id);

CREATE INDEX idx_tasks_user_story_id ON tasks (user_story_id);

-- ============================================================
-- DROP SPRINT_TASKS
-- ============================================================
DROP TABLE sprint_tasks;

-- ============================================================
-- TABLE: SPRINT RETROSPECTIVES
-- ============================================================
CREATE TABLE sprint_retrospectives (
                                       id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       sprint_id       NUMBER NOT NULL UNIQUE,
                                       summary         CLOB,
                                       what_went_well  CLOB,
                                       what_went_wrong CLOB,
                                       created_by      NUMBER NOT NULL,
                                       created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                       updated_by      NUMBER,
                                       updated_at      TIMESTAMP,
                                       CONSTRAINT fk_retro_sprint   FOREIGN KEY (sprint_id)  REFERENCES sprints (id),
                                       CONSTRAINT fk_retro_created  FOREIGN KEY (created_by) REFERENCES users (id),
                                       CONSTRAINT fk_retro_updated  FOREIGN KEY (updated_by) REFERENCES users (id),
                                       CONSTRAINT chk_retro_dates   CHECK (updated_at IS NULL OR updated_at >= created_at)
);

-- ============================================================
-- TABLE: STORY SPILLOVERS
-- ============================================================
CREATE TABLE story_spillovers (
                                  id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  sprint_story_id       NUMBER        NOT NULL,
                                  user_story_id         NUMBER        NOT NULL,
                                  origin_sprint_id      NUMBER        NOT NULL,
                                  destination_sprint_id NUMBER        NOT NULL,
                                  reason                VARCHAR2(50)  NOT NULL
                                      CHECK (reason IN (
                                                        'scope_change',
                                                        'blocked',
                                                        'underestimated',
                                                        'resource_unavailable',
                                                        'technical_issue',
                                                        'other'
                                          )),
                                  detail                VARCHAR2(1000),
                                  created_by            NUMBER        NOT NULL,
                                  created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  updated_by            NUMBER,
                                  updated_at            TIMESTAMP,
                                  CONSTRAINT fk_spill_sprint_story  FOREIGN KEY (sprint_story_id)       REFERENCES sprint_stories_assignments (id),
                                  CONSTRAINT fk_spill_story         FOREIGN KEY (user_story_id)         REFERENCES user_stories (id),
                                  CONSTRAINT fk_spill_origin        FOREIGN KEY (origin_sprint_id)      REFERENCES sprints (id),
                                  CONSTRAINT fk_spill_destination   FOREIGN KEY (destination_sprint_id) REFERENCES sprints (id),
                                  CONSTRAINT fk_spill_created       FOREIGN KEY (created_by)            REFERENCES users (id),
                                  CONSTRAINT fk_spill_updated       FOREIGN KEY (updated_by)            REFERENCES users (id),
                                  CONSTRAINT chk_spill_dates        CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE INDEX idx_spill_story_id ON story_spillovers (user_story_id);
CREATE INDEX idx_spill_origin   ON story_spillovers (origin_sprint_id);

-- ============================================================
-- TABLE: TECHNICAL DEBT
-- ============================================================
CREATE TABLE technical_debt (
                                id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                project_id    NUMBER        NOT NULL,
                                user_story_id NUMBER,
                                task_id       NUMBER,
                                title         VARCHAR2(255) NOT NULL,
                                description   CLOB,
                                debt_type     VARCHAR2(30)  NOT NULL
                                    CHECK (debt_type IN (
                                                         'code_quality',
                                                         'missing_tests',
                                                         'security',
                                                         'performance',
                                                         'documentation',
                                                         'architecture'
                                        )),
                                priority      VARCHAR2(10)  DEFAULT 'medium'
                                    CHECK (priority IN ('low', 'medium', 'high', 'critical')),
                                status        VARCHAR2(20)  DEFAULT 'open'
                                    CHECK (status IN ('open', 'in_progress', 'resolved', 'accepted')),
                                assigned_to   NUMBER        NOT NULL,
                                resolved_at   TIMESTAMP,
                                created_by    NUMBER        NOT NULL,
                                created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                updated_by    NUMBER,
                                updated_at    TIMESTAMP,
                                CONSTRAINT fk_debt_project  FOREIGN KEY (project_id)    REFERENCES projects (id),
                                CONSTRAINT fk_debt_story    FOREIGN KEY (user_story_id) REFERENCES user_stories (id),
                                CONSTRAINT fk_debt_task     FOREIGN KEY (task_id)       REFERENCES tasks (id),
                                CONSTRAINT fk_debt_assigned FOREIGN KEY (assigned_to)   REFERENCES users (id),
                                CONSTRAINT fk_debt_created  FOREIGN KEY (created_by)    REFERENCES users (id),
                                CONSTRAINT fk_debt_updated  FOREIGN KEY (updated_by)    REFERENCES users (id),
                                CONSTRAINT chk_debt_dates   CHECK (updated_at IS NULL OR updated_at >= created_at)
);

CREATE INDEX idx_debt_project_id ON technical_debt (project_id);
CREATE INDEX idx_debt_story_id   ON technical_debt (user_story_id);
CREATE INDEX idx_debt_status     ON technical_debt (status);